# Generated by Django 6.0.1 on 2026-01-29 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=255, verbose_name='Serviço/Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Detalhes do Serviço')),
                ('empresa', models.CharField(choices=[('proxmon', 'Proxmon'), ('eletros', 'Eletros')], default='proxmon', max_length=50)),
                ('ultima_atualizacao', models.TextField(blank=True, verbose_name='Status/Obs Atual')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('iniciado', 'Iniciado'), ('feito', 'Feito')], default='nao_iniciado', max_length=20)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.cliente')),
                ('tecnicos', models.ManyToManyField(blank=True, related_name='tarefas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
